name: autotest
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [^1.16.x]
        # os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
        os: [ubuntu-latest]
    name: build&test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -v
        working-directory: ./src/hello_fail
  send_result:
    if: always()
    needs: test
    name: send_webhook
    runs-on: ubuntu-latest
    steps:
      - name: Send Result To Webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json-extended'
          webhook_url: ${{ secrets.ZECREY_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.ZECREY_WEBHOOK_SECRET }}
          data: '{ "zecrey-result": true }'