name: go-autobuild
on: [push, pull_request]
jobs:
  build_test:
    strategy:
      matrix:
        go-version: [^1.16.x]
        # os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
        os: [ubuntu-latest]
    name: build&test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check version
        run: go version
      - name: Build
        run: go build
        working-directory: ./src
      - name: Test
        run: go test -v
        working-directory: ./src/hello
