name: try-golang-autobuild
on: [push, pull_request]
jobs:
  build_test:
    name: build&test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.8'
      - name: Check version
        run: go version
      - name: Build
        run: go build
        working-directory: ./src
      - name: Test
        run: go test -v
        working-directory: ./src/hello
